// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiAddEntryEntryPostData, ApiAddEntryEntryPostErrors, ApiAddEntryEntryPostResponses, ApiDeleteUserUserDeleteData, ApiDeleteUserUserDeleteErrors, ApiDeleteUserUserDeleteResponses, ApiFinalizeEntryFinalizePutData, ApiFinalizeEntryFinalizePutErrors, ApiFinalizeEntryFinalizePutResponses, ApiGetEntriesEntryMetadatasGetData, ApiGetEntriesEntryMetadatasGetErrors, ApiGetEntriesEntryMetadatasGetResponses, ApiGetEntryContentEntryContentGetData, ApiGetEntryContentEntryContentGetErrors, ApiGetEntryContentEntryContentGetResponses, ApiGetEntryEntryMetadataGetData, ApiGetEntryEntryMetadataGetErrors, ApiGetEntryEntryMetadataGetResponses, ApiLoginUserLoginPostData, ApiLoginUserLoginPostErrors, ApiLoginUserLoginPostResponses, ApiNewUserUserPostData, ApiNewUserUserPostErrors, ApiNewUserUserPostResponses, ApiRemoveEntryEntryDeleteData, ApiRemoveEntryEntryDeleteErrors, ApiRemoveEntryEntryDeleteResponses, ApiRestoreEntryEntryRestorePutData, ApiRestoreEntryEntryRestorePutErrors, ApiRestoreEntryEntryRestorePutResponses, ApiUpdateEntryEntryMetadataPutData, ApiUpdateEntryEntryMetadataPutErrors, ApiUpdateEntryEntryMetadataPutResponses, ApiUpdateUserUserPutData, ApiUpdateUserUserPutErrors, ApiUpdateUserUserPutResponses, GetMeUserGetData, GetMeUserGetErrors, GetMeUserGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all entries' metadata
 */
export const apiGetEntriesEntryMetadatasGet = <ThrowOnError extends boolean = false>(options: Options<ApiGetEntriesEntryMetadatasGetData, ThrowOnError>) => (options.client ?? client).get<ApiGetEntriesEntryMetadatasGetResponses, ApiGetEntriesEntryMetadatasGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entry/metadatas',
    ...options
});

/**
 * Get entry metadata
 */
export const apiGetEntryEntryMetadataGet = <ThrowOnError extends boolean = false>(options: Options<ApiGetEntryEntryMetadataGetData, ThrowOnError>) => (options.client ?? client).get<ApiGetEntryEntryMetadataGetResponses, ApiGetEntryEntryMetadataGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entry/metadata',
    ...options
});

/**
 * Update entry metadata
 */
export const apiUpdateEntryEntryMetadataPut = <ThrowOnError extends boolean = false>(options: Options<ApiUpdateEntryEntryMetadataPutData, ThrowOnError>) => (options.client ?? client).put<ApiUpdateEntryEntryMetadataPutResponses, ApiUpdateEntryEntryMetadataPutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entry/metadata',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get entry actual content
 */
export const apiGetEntryContentEntryContentGet = <ThrowOnError extends boolean = false>(options: Options<ApiGetEntryContentEntryContentGetData, ThrowOnError>) => (options.client ?? client).get<ApiGetEntryContentEntryContentGetResponses, ApiGetEntryContentEntryContentGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entry/content',
    ...options
});

/**
 * Mark entry as deleted
 */
export const apiRemoveEntryEntryDelete = <ThrowOnError extends boolean = false>(options: Options<ApiRemoveEntryEntryDeleteData, ThrowOnError>) => (options.client ?? client).delete<ApiRemoveEntryEntryDeleteResponses, ApiRemoveEntryEntryDeleteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entry/',
    ...options
});

/**
 * Add new entry
 */
export const apiAddEntryEntryPost = <ThrowOnError extends boolean = false>(options: Options<ApiAddEntryEntryPostData, ThrowOnError>) => (options.client ?? client).post<ApiAddEntryEntryPostResponses, ApiAddEntryEntryPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entry/',
    ...options
});

/**
 * Mark entry uploading process is done
 */
export const apiFinalizeEntryFinalizePut = <ThrowOnError extends boolean = false>(options: Options<ApiFinalizeEntryFinalizePutData, ThrowOnError>) => (options.client ?? client).put<ApiFinalizeEntryFinalizePutResponses, ApiFinalizeEntryFinalizePutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entry/finalize',
    ...options
});

/**
 * Remove "deleted" label
 */
export const apiRestoreEntryEntryRestorePut = <ThrowOnError extends boolean = false>(options: Options<ApiRestoreEntryEntryRestorePutData, ThrowOnError>) => (options.client ?? client).put<ApiRestoreEntryEntryRestorePutResponses, ApiRestoreEntryEntryRestorePutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entry/restore',
    ...options
});

/**
 * Delete this user
 */
export const apiDeleteUserUserDelete = <ThrowOnError extends boolean = false>(options: Options<ApiDeleteUserUserDeleteData, ThrowOnError>) => (options.client ?? client).delete<ApiDeleteUserUserDeleteResponses, ApiDeleteUserUserDeleteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/user/',
    ...options
});

/**
 * Get infomation about current user
 */
export const getMeUserGet = <ThrowOnError extends boolean = false>(options: Options<GetMeUserGetData, ThrowOnError>) => (options.client ?? client).get<GetMeUserGetResponses, GetMeUserGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/user/',
    ...options
});

/**
 * Register new user
 */
export const apiNewUserUserPost = <ThrowOnError extends boolean = false>(options: Options<ApiNewUserUserPostData, ThrowOnError>) => (options.client ?? client).post<ApiNewUserUserPostResponses, ApiNewUserUserPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update this user
 */
export const apiUpdateUserUserPut = <ThrowOnError extends boolean = false>(options: Options<ApiUpdateUserUserPutData, ThrowOnError>) => (options.client ?? client).put<ApiUpdateUserUserPutResponses, ApiUpdateUserUserPutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Grab the session id
 */
export const apiLoginUserLoginPost = <ThrowOnError extends boolean = false>(options: Options<ApiLoginUserLoginPostData, ThrowOnError>) => (options.client ?? client).post<ApiLoginUserLoginPostResponses, ApiLoginUserLoginPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/user/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
