// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * EntryPermission
 */
export type EntryPermission = 'private' | 'public' | 'public_readonly' | 'inclusive' | 'inclusive_readonly' | 'other';

/**
 * EntryType
 */
export type EntryType = 'file' | 'directory' | 'other';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginBody
 */
export type LoginBody = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * NewUser
 */
export type NewUser = {
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UpdateEntry
 */
export type UpdateEntry = {
    /**
     * Name
     */
    name: string | null;
    /**
     * Parent Id
     */
    parent_id: string | null;
    permission: EntryPermission | null;
    /**
     * Permission Inclusive
     */
    permission_inclusive: Array<string> | null;
};

/**
 * UpdateUser
 */
export type UpdateUser = {
    /**
     * Username
     */
    username: string | null;
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Password
     */
    password: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ApiGetEntriesEntryMetadatasGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * All
         */
        all?: boolean;
        /**
         * Parent Id
         */
        parent_id?: string | null;
    };
    url: '/entry/metadatas';
};

export type ApiGetEntriesEntryMetadatasGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiGetEntriesEntryMetadatasGetError = ApiGetEntriesEntryMetadatasGetErrors[keyof ApiGetEntriesEntryMetadatasGetErrors];

export type ApiGetEntriesEntryMetadatasGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiGetEntryEntryMetadataGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/entry/metadata';
};

export type ApiGetEntryEntryMetadataGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiGetEntryEntryMetadataGetError = ApiGetEntryEntryMetadataGetErrors[keyof ApiGetEntryEntryMetadataGetErrors];

export type ApiGetEntryEntryMetadataGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiUpdateEntryEntryMetadataPutData = {
    body: UpdateEntry;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/entry/metadata';
};

export type ApiUpdateEntryEntryMetadataPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiUpdateEntryEntryMetadataPutError = ApiUpdateEntryEntryMetadataPutErrors[keyof ApiUpdateEntryEntryMetadataPutErrors];

export type ApiUpdateEntryEntryMetadataPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiGetEntryContentEntryContentGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/entry/content';
};

export type ApiGetEntryContentEntryContentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiGetEntryContentEntryContentGetError = ApiGetEntryContentEntryContentGetErrors[keyof ApiGetEntryContentEntryContentGetErrors];

export type ApiGetEntryContentEntryContentGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiRemoveEntryEntryDeleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/entry/';
};

export type ApiRemoveEntryEntryDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiRemoveEntryEntryDeleteError = ApiRemoveEntryEntryDeleteErrors[keyof ApiRemoveEntryEntryDeleteErrors];

export type ApiRemoveEntryEntryDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiAddEntryEntryPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         */
        name: string;
        type: EntryType;
        /**
         * Parent Id
         */
        parent_id?: string | null;
    };
    url: '/entry/';
};

export type ApiAddEntryEntryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiAddEntryEntryPostError = ApiAddEntryEntryPostErrors[keyof ApiAddEntryEntryPostErrors];

export type ApiAddEntryEntryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiFinalizeEntryFinalizePutData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/entry/finalize';
};

export type ApiFinalizeEntryFinalizePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiFinalizeEntryFinalizePutError = ApiFinalizeEntryFinalizePutErrors[keyof ApiFinalizeEntryFinalizePutErrors];

export type ApiFinalizeEntryFinalizePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiRestoreEntryEntryRestorePutData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/entry/restore';
};

export type ApiRestoreEntryEntryRestorePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiRestoreEntryEntryRestorePutError = ApiRestoreEntryEntryRestorePutErrors[keyof ApiRestoreEntryEntryRestorePutErrors];

export type ApiRestoreEntryEntryRestorePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiDeleteUserUserDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/';
};

export type ApiDeleteUserUserDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiDeleteUserUserDeleteError = ApiDeleteUserUserDeleteErrors[keyof ApiDeleteUserUserDeleteErrors];

export type ApiDeleteUserUserDeleteResponses = {
    /**
     * Successful Response
     */
    200: {
        message?: string;
    };
};

export type ApiDeleteUserUserDeleteResponse = ApiDeleteUserUserDeleteResponses[keyof ApiDeleteUserUserDeleteResponses];

export type GetMeUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/';
};

export type GetMeUserGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeUserGetError = GetMeUserGetErrors[keyof GetMeUserGetErrors];

export type GetMeUserGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiNewUserUserPostData = {
    body: NewUser;
    path?: never;
    query?: never;
    url: '/user/';
};

export type ApiNewUserUserPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiNewUserUserPostError = ApiNewUserUserPostErrors[keyof ApiNewUserUserPostErrors];

export type ApiNewUserUserPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiUpdateUserUserPutData = {
    body: UpdateUser;
    path?: never;
    query?: never;
    url: '/user/';
};

export type ApiUpdateUserUserPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiUpdateUserUserPutError = ApiUpdateUserUserPutErrors[keyof ApiUpdateUserUserPutErrors];

export type ApiUpdateUserUserPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiLoginUserLoginPostData = {
    body: LoginBody;
    path?: never;
    query?: {
        /**
         * Expire Time
         */
        expire_time?: string;
    };
    url: '/user/login';
};

export type ApiLoginUserLoginPostErrors = {
    /**
     * Unauthorized
     */
    401: {
        detail?: {
            message?: string;
        };
    };
    /**
     * Not Found
     */
    404: {
        detail?: {
            message?: string;
        };
    };
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiLoginUserLoginPostError = ApiLoginUserLoginPostErrors[keyof ApiLoginUserLoginPostErrors];

export type ApiLoginUserLoginPostResponses = {
    /**
     * Successful Response
     */
    200: {
        message?: string;
    };
};

export type ApiLoginUserLoginPostResponse = ApiLoginUserLoginPostResponses[keyof ApiLoginUserLoginPostResponses];
